### ISSUE TITLE
Combining multiple plug-ins

### ISSUE THREAD

**Issue by houda96** [gsssrao/UnityAndroidSpeechRecognition#4]
Hi,

We are trying to integrate your code with Google Tango, which means there are two plugins. Combining the two manifest files has failed and the mentioned resources did also not work. Do you happen to already fixed this issue or do you have some markers on it?

**Comment by gsssrao** [comment]
Hi @houda96, 

Yes, if you have two different plugins both extending unity player activity and two manifests then you will face issues. 

Do you have android development experience using Android Studio? If yes, then a simple way to solve this issue is to include the [speech recognition code](https://github.com/gsssrao/UnityAndroidSpeechRecognition/tree/master/SpeechPlugin/pluginlibrary/src/main/java/com/plugin/speech/pluginlibrary) into the tango plugin and re-creating the jar. Basically, your tango plugin too would have a jar or aar file in the plugins folder in which there would be a java class which extends UnityPlayerActivity. So instead of having [this file](https://github.com/gsssrao/UnityAndroidSpeechRecognition/blob/master/SpeechPlugin/pluginlibrary/src/main/java/com/plugin/speech/pluginlibrary/ActivityClass.java) you just need to append parts of it into tango java class which extends UnityPlayerActivity. And then you can have a separate class file to call it like [this one](https://github.com/gsssrao/UnityAndroidSpeechRecognition/blob/master/SpeechPlugin/pluginlibrary/src/main/java/com/plugin/speech/pluginlibrary/TestPlugin.java). 

Once you do this, you just need to the recreate the jar file and replace it with the original tango jar file in Unity (To understand how the jar creation and inclusion in Unity work, you can probably start from [here](https://github.com/gsssrao/UnityAndroidSpeechRecognition#Experimenting) ). 

Note: If you change names of the java files or their functions, you will have to modify the code in the csharp files in Unity as well to match those names.

**Comment by houda96** [comment]
Hi,

Thank you for the answer. Sadly, we do not have experience with android development. Since, we are using this as part of a four week course, we do not have time to explore this more in depth. We found a work around to process this in Python. We will definitely keep this in mind, when we would upgrade the app when more time is available. It may be of use for others.

**Comment by gsssrao** [comment]
Sure.
